sudo: required
os:
  - linux
  - osx
before_install:
  - npm  i
env:
  - NODEEXE= process.execPath
script:
  - $NODEEXE test/server-test.js -- --coverage
  - $NODEEXE test/subset-test.js -- --coverage
